# Generated by Django 3.2.11 on 2022-01-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('serve_date', 'restaurant')},
        ),
    ]
